import * as fs from "fs";
import * as path from "path";
import express from "express";
import session from "express-session";
import passport from "passport";
import rateLimit from "express-rate-limit";
import {
  Strategy as SamlStrategy,
  SamlConfig,
  VerifyWithRequest,
} from "@node-saml/passport-saml";

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

const SP_PORT = parseInt(process.env.SP_PORT ?? "3000", 10);
const IDP_SSO_URL =
  process.env.IDP_SSO_URL ?? "http://localhost:7000/saml/sso";
const IDP_ISSUER = process.env.IDP_ISSUER ?? "urn:example:idp";
const SP_ISSUER = process.env.SP_ISSUER ?? "urn:example:sp";
const SP_CALLBACK_URL =
  process.env.SP_CALLBACK_URL ?? `http://localhost:${SP_PORT}/login/callback`;

// Load certificates (generated by `yarn cert`)
const certsDir = path.resolve(__dirname, "../../certs");

function loadCert(filename: string): string {
  const fullPath = path.join(certsDir, filename);
  if (!fs.existsSync(fullPath)) {
    throw new Error(
      `Certificate not found: ${fullPath}. Run 'yarn cert' first.`
    );
  }
  return fs.readFileSync(fullPath, "utf8");
}

const spKey = loadCert("sp.key");
const spCert = loadCert("sp.crt");
const idpCert = loadCert("idp.crt");

// ---------------------------------------------------------------------------
// Passport / SAML strategy
// ---------------------------------------------------------------------------

interface SamlUser {
  nameID: string;
  nameIDFormat?: string;
  sessionIndex?: string;
  attributes: Record<string, string | string[]>;
  [key: string]: unknown;
}

const samlConfig: SamlConfig = {
  callbackUrl: SP_CALLBACK_URL,
  entryPoint: IDP_SSO_URL,
  issuer: SP_ISSUER,
  idpCert,
  privateKey: spKey,
  // Validate the IdP's SAML response
  wantAssertionsSigned: true,
};

const signonVerify: VerifyWithRequest = (
  _req,
  profile,
  done
) => {
  if (!profile) {
    return done(new Error("No SAML profile received"));
  }
  const user: SamlUser = {
    nameID: profile.nameID,
    nameIDFormat: profile.nameIDFormat,
    sessionIndex: profile.sessionIndex,
    attributes: (profile.attributes as Record<string, string | string[]>) ?? {},
  };
  return done(null, user);
};

const logoutVerify: VerifyWithRequest = (
  _req,
  profile,
  done
) => {
  if (!profile) {
    return done(new Error("No SAML profile received"));
  }
  done(null);
};

// Keep a reference to the strategy so it can be used directly (e.g. for
// generating SP metadata) without relying on passport's internal _strategy map.
const samlStrategy = new SamlStrategy(samlConfig, signonVerify, logoutVerify);

// passport-saml bundles its own express@4 types which are not assignable to
// passport's express@5-typed Strategy interface, so we cast here.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
passport.use(samlStrategy as any);

passport.serializeUser((user, done) => done(null, user));
passport.deserializeUser((user: Express.User, done) => done(null, user));

// ---------------------------------------------------------------------------
// Express app
// ---------------------------------------------------------------------------

const app = express();

app.use(express.urlencoded({ extended: false }));
app.use(
  session({
    secret: process.env.SESSION_SECRET ?? "saml-experiment-secret",
    resave: false,
    saveUninitialized: false,
    cookie: {
      httpOnly: true,
      // Enable 'secure' in production (requires HTTPS)
      secure: process.env.NODE_ENV === "production",
      sameSite: "lax",
    },
  })
);
app.use(passport.initialize());
app.use(passport.session());

// Apply a global rate limit to all routes
app.use(
  rateLimit({
    windowMs: 15 * 60 * 1000, // 15 minutes
    max: 100,
    standardHeaders: true,
    legacyHeaders: false,
  })
);

// Stricter rate limit for the authentication endpoints
const loginLimiter = rateLimit({
  windowMs: 15 * 60 * 1000, // 15 minutes
  max: 20,
  standardHeaders: true,
  legacyHeaders: false,
});

// Home – requires authentication
app.get("/", (req, res) => {
  if (!req.isAuthenticated()) {
    return res.redirect("/login");
  }
  const user = req.user as SamlUser;
  res.send(
    `<h1>Logged in via SAML</h1>
     <p><strong>NameID:</strong> ${user.nameID}</p>
     <pre>${JSON.stringify(user.attributes, null, 2)}</pre>
     <a href="/logout">Logout</a>`
  );
});

// Initiate SAML login
app.get(
  "/login",
  loginLimiter,
  passport.authenticate("saml", { failureRedirect: "/error" })
);

// SAML assertion consumer service (ACS)
app.post(
  "/login/callback",
  loginLimiter,
  passport.authenticate("saml", { failureRedirect: "/error" }),
  (_req, res) => {
    res.redirect("/");
  }
);

// SP-initiated logout
app.get("/logout", (req, res, next) => {
  req.logout((err) => {
    if (err) return next(err);
    res.redirect("/");
  });
});

// Service-provider metadata (useful when registering the SP with an IdP)
app.get("/metadata", (_req, res) => {
  const metadata = samlStrategy.generateServiceProviderMetadata(spCert, spCert);
  res.type("application/xml").send(metadata);
});

app.get("/error", (_req, res) => {
  res.status(401).send("<h1>Authentication failed</h1><a href='/login'>Try again</a>");
});

app.listen(SP_PORT, () => {
  console.log(`SP listening on http://localhost:${SP_PORT}`);
  console.log(`  SP metadata: http://localhost:${SP_PORT}/metadata`);
  console.log(`  IdP SSO URL: ${IDP_SSO_URL}`);
});
